# Generated by Django 5.2.5 on 2025-08-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('telefono', models.CharField(max_length=20)),
                ('alergia', models.BooleanField(default=False)),
                ('descripcion_alergia', models.CharField(blank=True, max_length=200)),
                ('plan', models.CharField(choices=[('D', 'Diario'), ('S', 'Semanal'), ('M', 'Mensual')], max_length=1)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, max_length=300)),
            ],
        ),
    ]
