# Generated by Django 5.2.5 on 2025-08-07 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_plan_alter_member_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membershipplan'),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
