# Generated by Django 5.2.5 on 2025-08-07 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_add_default_plans'),
        ('members', '0004_alter_member_plan_delete_plan'),
    ]

    operations = [
    ]
