# Generated by Django 5.2.5 on 2025-08-07 01:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('members', '0002_membershipplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 7, 1, 38, 27, 249419, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
    ]
